name: GitHub Metrics

on:
  schedule: [{ cron: '0 14 * * *' }]
  # Lines below let you run workflow manually and on each commit
  workflow_dispatch:
  push: { branches: ['master', 'main'] }

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - name: general
        if: ${{ success() || failure() }}
        uses: lowlighter/metrics@latest
        with:
          filename: general.svg
          output_action: gist
          committer_gist: ${{ secrets.METRICS_GENERAL_GIST }}

          # GitHub token
          token: ${{ secrets.GH_PAT }}

          # Options
          template: classic
          base: header
          config_timezone: ${{ secrets.METRICS_TIMEZONE }}
          config_order: base.header, languages, isocalendar, topics

          # languages
          plugin_languages: yes
          plugin_languages_ignored: ${{ secrets.METRICS_IGNORED_LANG }}
          plugin_languages_skipped: ${{ secrets.METRICS_SKIPPED_REPO }}
          plugin_languages_analysis_timeout: 60
          plugin_languages_categories: markup, programming
          plugin_languages_recent_categories: markup, programming
          plugin_languages_recent_load: 1000
          plugin_languages_colors: github
          plugin_languages_limit: 0
          plugin_languages_sections: most-used, recently-used
          plugin_languages_details: percentage, lines, bytes-size
          plugin_languages_threshold: 0%
          plugin_languages_other: yes
          plugin_languages_recent_days: 30

          # isocalendar
          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year

          # topics
          plugin_topics: yes
          plugin_topics_limit: 0
          plugin_topics_mode: icons
          plugin_topics_sort: random
