name: Waka

on:
  schedule: [{ cron: '0 14 * * *' }]
  # Lines below let you run workflow manually and on each commit
  workflow_dispatch:
  push: { branches: ['master', 'main'] }

jobs:
  waka:
    runs-on: ubuntu-latest
    steps:
      - name: update waka
        uses: athul/waka-readme@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          SHOW_TITLE: True
          SHOW_TOTAL: True
          BLOCKS: ⣀⣄⣤⣦⣶⣷⣿
          COMMIT_MESSAGE: Update Waka [skip ci]

      # - name: update waka
      #   uses: anmol098/waka-readme-stats@master # https://github.com/anmol098/waka-readme-stats/issues/425
      #   with:
      #     WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
      #     GH_TOKEN: ${{ secrets.GH_PAT }}
      #     SHOW_OS: False
      #     SHOW_EDITORS: False
      #     SHOW_DAYS_OF_WEEK: False
      #     SHOW_PROJECTS: False
      #     SHOW_LANGUAGE_PER_REPO: False
      #     SHOW_LOC_CHART: False
      #     SHOW_TIMEZONE: False
      #     SHOW_SHORT_INFO: False
      #     SHOW_UPDATED_DATE: False
      #     SYMBOL_VERSION: 2
      #     LOCALE: en
      #     COMMIT_MESSAGE: Update Waka [skip ci]
      #     DEBUG_LOGGING: True
